### PR TITLE
Fix #1057 and add unit test

### LINKED ISSUE #1057: Trying to get createdAt of an MkComment throws IllegalStateException
See https://gist.github.com/cvrebert/fbf0f030515bd272b54e

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #1057.

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@longtimeago this pull request is for you, please review

File: src/main/java/com/jcabi/github/mock/MkComments.java [hunk 1]
```diff
@@ -146,15 +146,22 @@ public Comment post(
...
                 new Directives().xpath(this.xpath()).add("comment")
                     .add("number").set(Integer.toString(number)).up()
+                    .add("url").set(url).up()
                     .add("body").set(text).up()
-                    .add("user").add("login").set(this.self).up()
-                    .add("created_at").set(new Github.Time().toString()).up()
-                    .add("updated_at").set(new Github.Time().toString())
+                    .add("user")
+                        .add("login").set(this.self).up()
+                    .up()
```
Comment (cvrebert) [inline src/main/java/com/jcabi/github/mock/MkComments.java]: The bug was that this `.up()` was missing.

File: src/test/java/com/jcabi/github/mock/MkCommentTest.java [hunk 2]
```diff
@@ -43,6 +45,10 @@
  * @version $Id$
  */
 public final class MkCommentTest {
+    /**
+     * Example issue comment text.
+     */
+    private static final String COMMENT_TEXT = "what's up?";
```
Comment (longtimeago) [inline src/test/java/com/jcabi/github/mock/MkCommentTest.java]: @cvrebert no need in this field. Just use different comments in places where we need them

File: src/test/java/com/jcabi/github/mock/MkCommentTest.java [hunk 3]
```diff
@@ -90,6 +96,57 @@ public void canCompareInstances() throws Exception {
...
+        );
+        MatcherAssert.assertThat(
+            smart.author().login(),
+            Matchers.equalTo("jeff")
+        );
+        MatcherAssert.assertThat(
+            smart.body(),
+            Matchers.equalTo(COMMENT_TEXT)
+        );
+        final String domain = "https://api.jcabi-github.invalid";
```
Comment (longtimeago) [inline src/test/java/com/jcabi/github/mock/MkCommentTest.java]: @cvrebert one-time variable. Can be inlined

File: src/test/java/com/jcabi/github/mock/MkCommentTest.java [hunk 4]
```diff
@@ -90,6 +96,57 @@ public void canCompareInstances() throws Exception {
...
+        final String path = "/repos/jeff/test/issues/comments/1";
```
Comment (longtimeago) [inline src/test/java/com/jcabi/github/mock/MkCommentTest.java]: @cvrebert same here

File: src/test/java/com/jcabi/github/mock/MkCommentTest.java [hunk 5]
```diff
@@ -90,6 +96,57 @@ public void canCompareInstances() throws Exception {
...
+        MatcherAssert.assertThat(
+            smart.url(),
+            Matchers.equalTo(new URL(domain + path))
```
Comment (longtimeago) [inline src/test/java/com/jcabi/github/mock/MkCommentTest.java]: @cvrebert no need to join strings, full url can be inlined right here

File: src/test/java/com/jcabi/github/mock/MkCommentTest.java (hunk 3 above)
Comment (cvrebert) [inline src/test/java/com/jcabi/github/mock/MkCommentTest.java]: @longtimeago The string hits the line-length limit or "don't concat constant strings" qulice checks otherwise. Can you suggest an alternative?

File: src/test/java/com/jcabi/github/mock/MkCommentTest.java (hunk 5 above)
Comment (cvrebert) [inline src/test/java/com/jcabi/github/mock/MkCommentTest.java]: @longtimeago That exceeds the line length limit.

File: src/test/java/com/jcabi/github/mock/MkCommentTest.java (hunk 2 above)
Comment (cvrebert) [inline src/test/java/com/jcabi/github/mock/MkCommentTest.java]: @longtimeago Done.

File: src/test/java/com/jcabi/github/mock/MkCommentTest.java (hunk 5 above)
Comment (longtimeago) [inline src/test/java/com/jcabi/github/mock/MkCommentTest.java]: @cvrebert ``` // @checkstyle LineLength (1 line) ``` is the best alternative in this case

**Comment by cvrebert** [comment]
@longtimeago Okay, I've addressed all your comments.

File: src/test/java/com/jcabi/github/mock/MkCommentTest.java [hunk 6]
```diff
@@ -90,14 +91,76 @@ public void canCompareInstances() throws Exception {
...
+            Matchers.equalTo("jeff")
+        );
+        MatcherAssert.assertThat(
+            smart.body(),
+            Matchers.equalTo(cmt)
+        );
+        MatcherAssert.assertThat(
+            smart.url(),
+            // @checkstyle LineLength (1 line)
+            Matchers.equalTo(new URL("https://api.jcabi-github.invalid/repos/jeff/test/issues/comments/1"))
```
Comment (longtimeago) [inline src/test/java/com/jcabi/github/mock/MkCommentTest.java]: @cvrebert Actually, it's better to format this line following way:
```java
		Matchers.equalTo(
				new URL(
						"https://api.jcabi-github.invalid/repos/jeff/test/issues/comments/1"
				)
		)
```
Sorry, we are very pedantic :)

File: src/test/java/com/jcabi/github/mock/MkCommentTest.java [hunk 7]
```diff
@@ -90,14 +91,76 @@ public void canCompareInstances() throws Exception {
...
             Json.createObjectBuilder().add("name", "test").build()
-        ).issues().create("hey", "how are you?").comments().post("what's up?");
+        ).issues().create("hey", "how are you?").comments().post(text);
     }
 
+    /**
+     * Obtains the current time.
+     * @return Current time (in milliseconds since epoch) truncated to the nearest second
+     */
+    private long now() {
```
Comment (longtimeago) [inline src/test/java/com/jcabi/github/mock/MkCommentTest.java]: @cvrebert this can be static, as we don't use any field

File: src/test/java/com/jcabi/github/mock/MkCommentTest.java [hunk 8]
```diff
@@ -90,14 +91,76 @@ public void canCompareInstances() throws Exception {
...
+        final int mspersec = 1000;
+        final long sinceepoch = new Date().getTime();
+        final long milliseconds = sinceepoch % mspersec;
+        return sinceepoch - milliseconds;
```
Comment (longtimeago) [inline src/test/java/com/jcabi/github/mock/MkCommentTest.java]: @cvrebert all these things can be done in one line
```java
return new Date().getTime() - sinceepoch % 1000;
```
without any one-time-variable.
The code is still understandable. Javadoc explains what is going on.

By the way, why do we need this truncation?

File: src/test/java/com/jcabi/github/mock/MkCommentTest.java (hunk 6 above)
Comment (cvrebert) [inline src/test/java/com/jcabi/github/mock/MkCommentTest.java]: @longtimeago Fixed

File: src/test/java/com/jcabi/github/mock/MkCommentTest.java (hunk 7 above)
Comment (cvrebert) [inline src/test/java/com/jcabi/github/mock/MkCommentTest.java]: @longtimeago Fixed.

**Comment by longtimeago** [comment]
@cvrebert looks like we need one more round :)

**Comment by cvrebert** [comment]
@longtimeago Already pushed :)

File: src/test/java/com/jcabi/github/mock/MkCommentTest.java (hunk 8 above)
Comment (cvrebert) [inline src/test/java/com/jcabi/github/mock/MkCommentTest.java]: @longtimeago Done.
It's needed because comment created_at timestamps seem to be stored at second-level granularity.

**Comment by longtimeago** [comment]
@cvrebert you are too fast. Let me write all remarks :)

**Comment by cvrebert** [comment]
I'm trying to get your "LGTM" ASAP. :smile: 
jcabi-github bugs are what's blocking me from launching my project...

File: src/main/java/com/jcabi/github/mock/MkComments.java [hunk 9]
```diff
@@ -146,15 +146,22 @@ public Comment post(
...
+            final String timestamp = new Github.Time().toString();
+            final String userrepo = this.repo.user() + "/" + this.repo.repo();
             number = 1 + this.storage.xml()
                 .nodes("//comment/number").size();
+            final String url = "https://api.jcabi-github.invalid/repos/"
+                + userrepo + "/issues/comments/" + number;
             this.storage.apply(
                 new Directives().xpath(this.xpath()).add("comment")
                     .add("number").set(Integer.toString(number)).up()
+                    .add("url").set(url).up()
```
Comment (longtimeago) [inline src/main/java/com/jcabi/github/mock/MkComments.java]: let's avoid using one-time variables. Please, inline url here as following:
```java
.add("url")
.set(
   String.format(
       "https://api.jcabi-github.invalid/repos/%s/%s/issues/comments/%d", 
        this.repo.user(),
        this.repo.repo(),
        number
   )
)
```

and remove ```userrepo``` and ```url``` variables

**Comment by longtimeago** [comment]
@cvrebert ok, the last remark and we are done :)
(at least with me, because next review would be by the project owner)

Sorry, if this blocks your project, but we must be sure the code is clean before push

**Comment by cvrebert** [comment]
@longtimeago Okay, I've applied your last comment.

**Comment by longtimeago** [comment]
@cvrebert and checkstyle beated again :)
1000 can be replaced with ```Tv.THOUSAND```
With other things you know to do :)

**Comment by cvrebert** [comment]
@longtimeago Done.

**Comment by longtimeago** [comment]
@rultor merge please
@cvrebert thank you!

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.1`

**Comment by dmarkov** [comment]
@longtimeago thanks, I just added **20 mins** to your account, payment `55538997`, 42 hours and 51 mins spent. review comments (c=5) added as a bonus. +20 added to your rating, current score is: [+4331](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy
