### PR TITLE
Use fake webhook instead of geocommit for Hook tests

### LINKED ISSUE #1104: RtHooksITCase is now failing since geocommit has gone offline
`geocommit` has gone offline and been removed from GitHub's list of services: https://github.com/github/github-services/pull/1052/files#diff-a239e193db531f93c7c3ad725aff5195
This is causing `RtHooksITCase` to fail since the test hooks it creates were for `geocommit`: https://github.com/jcabi/jcabi-github/pull/1100#issuecomment-108114012
Probably it should just use a `web` hook instead.
API docs: https://developer.github.com/v3/repos/hooks/#create-a-hook

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #1104. \*grumbles*
/cc @yegor256

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert Thanks for the pull request, let me find a reviewer..

**Comment by dmarkov** [comment]
@pinaf could you please review this pull request

**Comment by cvrebert** [comment]
@pinaf Ping.

File: src/main/java/com/jcabi/github/Hooks.java [hunk 1]
```diff
@@ -81,13 +81,16 @@
      * Create new hook.
      * @param name Hook name
      * @param config Configuration for the hook
+     * @param active Actually trigger the hook when the events occur?
      * @return Hook
      * @throws IOException If there is any I/O problem
      * @see <a href="http://developer.github.com/v3/repos/hooks/#create-a-hook">Create a hook</a>
+     * @todo #1106:30min Add support for the "events" parameter.
```
Comment (pinaf) [inline src/main/java/com/jcabi/github/Hooks.java]: @cvrebert this puzzle description is too short. the minimum length is 20 words - please expand a little bit.

File: src/test/java/com/jcabi/github/RtHooksITCase.java [hunk 2]
```diff
@@ -146,9 +148,22 @@ private static Repos repos() {
      * @throws IOException If there is any I/O problem
      */
     private static Hook createHook(final Repo repo) throws IOException {
+        final ConcurrentHashMap<String, String> config =
```
Comment (pinaf) [inline src/test/java/com/jcabi/github/RtHooksITCase.java]: @cvrebert can't we change the declared variable type to `Map`?

File: src/test/java/com/jcabi/github/mock/MkHooksTest.java [hunk 3]
```diff
@@ -108,10 +112,14 @@ public void canFetchNonEmptyListOfHooks() throws Exception {
         final Hooks hooks = MkHooksTest.repo().hooks();
         hooks.create(
             // @checkstyle MultipleStringLiterals (1 line)
```
Comment (pinaf) [inline src/test/java/com/jcabi/github/mock/MkHooksTest.java]: @cvrebert does this string literal `"web"` have to be the same for all tests? If so, let's extract it to a `private static final` field and remove the checkstyle suppresions. If not, let's have different string literals for each test.

**Comment by pinaf** [comment]
@cvrebert 3 comments above.

File: src/test/java/com/jcabi/github/mock/MkHooksTest.java (hunk 3 above)
Comment (cvrebert) [inline src/test/java/com/jcabi/github/mock/MkHooksTest.java]: Yes, it must be the same.

File: src/test/java/com/jcabi/github/RtHooksITCase.java (hunk 2 above)
Comment (cvrebert) [inline src/test/java/com/jcabi/github/RtHooksITCase.java]: @pinaf That would cause [PMD UseConcurrentHashMap](http://pmd.sourceforge.net/pmd-4.3.0/rules/controversial.html) qulice error.

File: src/test/java/com/jcabi/github/mock/MkHooksTest.java (hunk 3 above)
Comment (cvrebert) [inline src/test/java/com/jcabi/github/mock/MkHooksTest.java]: @pinaf Done.

File: src/main/java/com/jcabi/github/Hooks.java (hunk 1 above)
Comment (cvrebert) [inline src/main/java/com/jcabi/github/Hooks.java]: @pinaf Done.

**Comment by cvrebert** [comment]
@pinaf Responded to your 3 comments.

**Comment by pinaf** [comment]
@cvrebert why the new method `newHooks`?

**Comment by cvrebert** [comment]
@pinaf Because (1) the `repo` was only used for its `hooks`, so this removes some redundancy in the code (2) to avoid conflicting with `hooks` local vars

**Comment by pinaf** [comment]
@cvrebert makes sense. thank you.

**Comment by pinaf** [comment]
@rultor merge

**Comment by cvrebert** [comment]
@yegor256 Please, merge.

**Comment by cvrebert** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by dmarkov** [comment]
@pinaf I added **19 mins** to your account, many thanks for working with the project! The completion time here was AP-9W123701P02472019.

review comments (c=4) added as a bonus

+19 added to your rating, at the moment it is: [+6529](http://www.netbout.com/b/35128?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Comment by dmarkov** [comment]
@cvrebert the code made here contains a puzzle `1106-3aa88d70`/#1115, which will be resolved soon

**Comment by 0pdd** [comment]
@cvrebert the only puzzle [#unknown]() is solved here.
